#!/bin/bash
set -euo pipefail

echo ">>> Stage 03: Shell personalization (bash primary + zsh compatibility)"

# Target user home
USER_HOME="/home/mark"
if [ ! -d "$USER_HOME" ]; then
    echo "❌ User mark home directory not found - skipping"
    exit 1
fi

# ==================== .bashrc (primary - fully owned by bootstrap) ====================
BASHRC="${USER_HOME}/.bashrc"

cat > "$BASHRC" << 'EOF'
# ================================================
# Mark's Home VM - .bashrc
# Generated by bootstrap stage 03 - safe to rerun
# Preferred shell: bash (as refactored)
# ================================================

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# History settings
HISTCONTROL=ignoreboth:erasedups
HISTSIZE=10000
HISTFILESIZE=20000
shopt -s histappend
shopt -s checkwinsize

# Editor
export EDITOR=nano
export VISUAL=nano

# Pager
export PAGER="less -R"

# Preferred tools aliases
alias ll='ls -alF --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias cat='bat -p'                    # bat as plain cat (no pager)
alias vim='nvim'
alias vi='nvim'
alias gs='git status --short'
alias ga='git add'
alias gc='git commit -v'
alias update='sudo apt update && sudo apt upgrade -y'

# Enable color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Starship prompt 
 if command -v starship >/dev/null 2>&1; then
     eval "$(starship init bash)"
 fi

echo "✓ Mark's bashrc loaded (bootstrap v1)"
EOF

chown mark:mark "$BASHRC"
chmod 644 "$BASHRC"

# ==================== .zshrc (compatibility only - in case you ever switch) ====================
ZSHRC="${USER_HOME}/.zshrc"

cat > "$ZSHRC" << 'EOF'
# Mark's .zshrc - compatibility layer only
# (you refactored to bash as default, but zsh is still installed)
# Sources .bashrc so most aliases/settings are shared

[[ -f ~/.bashrc ]] && . ~/.bashrc

# Starship (will be enabled in next stage)
# if command -v starship >/dev/null 2>&1; then
#     eval "$(starship init zsh)"
# fi

echo "✓ Mark's zshrc loaded (bash compatibility)"
EOF

chown mark:mark "$ZSHRC"
chmod 644 "$ZSHRC"

# Make sure user shell is still bash (in case stage 01 was changed)
if [ "$(getent passwd mark | cut -d: -f7)" != "/bin/bash" ]; then
    chsh -s /bin/bash mark
    echo "✓ Switched user mark default shell to bash"
fi

echo "✓ Stage 03 complete - bash personalized (zsh compat included)"
