#!/usr/bin/env bash
set -euo pipefail

echo "🪄 Stage 03: Shell personalization (Bash only) — tuning the voice of the terminal..."

USER_HOME="/home/mark"
[ -d "$USER_HOME" ] || { echo "❌ User home not found — skipping."; exit 1; }

BASHRC="${USER_HOME}/.bashrc"
cat > "$BASHRC" << 'EOF'
# === Mark's Home VM - .bashrc ===
# Generated by bootstrap stage 03 — safe to rerun
case $- in *i*) ;; *) return;; esac

HISTCONTROL=ignoreboth:erasedups
HISTSIZE=10000; HISTFILESIZE=20000
shopt -s histappend checkwinsize

export EDITOR=nvim VISUAL=nvim
export PAGER="less -R"

alias ll='ls -alF --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias cat='bat -p'
alias vim='nvim'; alias vi='nvim'
alias gs='git status --short'
alias ga='git add'
alias gc='git commit -v'
alias update='sudo apt update && sudo apt upgrade -y'

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

if command -v starship >/dev/null 2>&1; then
    eval "$(starship init bash)"
fi


# Display MOTD when starting a new tmux session
if [[ -n "$TMUX" ]]; then
    run-parts --lsbsysinit /etc/update-motd.d/ 2>/dev/null || true
fi


EOF
chown mark:mark "$BASHRC"; chmod 644 "$BASHRC"

# Ensure default shell is bash
if [ "$(getent passwd mark | cut -d: -f7)" != "/bin/bash" ]; then
    chsh -s /bin/bash mark
fi

echo "✨ Stage 03 complete! Bash is tailored and singing."
