#!/bin/bash
set -euo pipefail

echo ">>> Stage 04: Starship prompt + terminal compatibility fix"

# Target user home
USER_HOME="/home/mark"
if [ ! -d "$USER_HOME" ]; then
    echo "❌ User mark home directory not found - skipping"
    exit 1
fi

# ==================== Fix terminal error you just hit (Alacritty) ====================
echo "Installing ncurses-term (fixes 'Error opening terminal: alacritty' for nano/nvim/etc.)"
apt-get update -qq
apt-get install -y -qq ncurses-term

# ==================== Install Starship (official method - idempotent) ====================
if ! command -v starship >/dev/null 2>&1; then
    echo "Installing starship..."
    curl -sS https://starship.rs/install.sh | sh -s -- --yes
    echo "✓ Starship installed successfully"
else
    echo "✓ Starship already installed"
fi

# ==================== Enable in .bashrc (append only if missing) ====================
BASHRC="${USER_HOME}/.bashrc"
if ! grep -q "starship init bash" "$BASHRC" 2>/dev/null; then
    cat >> "$BASHRC" << 'EOF'

# Starship prompt (added by bootstrap stage 04)
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init bash)"
fi
EOF
    echo "✓ Starship enabled in .bashrc"
else
    echo "✓ Starship already configured in .bashrc"
fi

# ==================== Enable in .zshrc (append only if missing) ====================
ZSHRC="${USER_HOME}/.zshrc"
if ! grep -q "starship init zsh" "$ZSHRC" 2>/dev/null; then
    cat >> "$ZSHRC" << 'EOF'

# Starship prompt (added by bootstrap stage 04 - compatibility)
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init zsh)"
fi
EOF
    echo "✓ Starship enabled in .zshrc"
else
    echo "✓ Starship already configured in .zshrc"
fi

# ==================== Create nice default starship.toml (only once) ====================
mkdir -p "${USER_HOME}/.config"
STARSHIP_TOML="${USER_HOME}/.config/starship.toml"

if [ ! -f "$STARSHIP_TOML" ]; then
    cat > "$STARSHIP_TOML" << 'EOF'
# ================================================
# Mark's Starship config - clean & modern
# Generated by bootstrap stage 04 - safe to customize later
# ================================================

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style)@"

[hostname]
style = "bold yellow"
ssh_only = false
format = "[$hostname]($style) "

[directory]
truncation_length = 3
style = "bold cyan"

[git_branch]
style = "bold purple"

[git_status]
style = "bold red"

[cmd_duration]
style = "bold yellow"
min_time = 500

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
EOF
    echo "✓ Default starship.toml created"
else
    echo "✓ starship.toml already exists (keeping your version)"
fi

chown -R mark:mark "${USER_HOME}/.config"

echo "✓ Stage 04 complete!"
echo "   Starship prompt is now active."
echo "   (Run: source $BASHRC   or just reconnect via SSH to see the new prompt)"
echo "   ncurses-term fix applied → nano/nvim will work perfectly from Alacritty now"
