#!/bin/bash
set -euo pipefail

echo ">>> Stage 05: tmux auto-start on SSH login"

# Target user home
USER_HOME="/home/mark"
if [ ! -d "$USER_HOME" ]; then
    echo "❌ User mark home directory not found - skipping"
    exit 1
fi

# Ensure tmux is installed (idempotent - stage 02 already did this)
apt-get update -qq
apt-get install -y -qq tmux

# ==================== Nice default .tmux.conf (only once) ====================
TMUX_CONF="${USER_HOME}/.tmux.conf"
if [ ! -f "$TMUX_CONF" ]; then
    cat > "$TMUX_CONF" << 'EOF'
# ================================================
# Mark's tmux config - modern & comfortable
# Generated by bootstrap stage 05
# ================================================

# Use 256 colors and truecolor support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when one is closed
set -g renumber-windows on

# Faster key repeat
set -s escape-time 0

# Status bar - simple & clean (works great with starship)
set -g status-style "bg=#282c34,fg=#abb2bf"
set -g status-left-length 30
set -g status-right "#[fg=#61afef]%H:%M #[fg=#98c379]%d-%b-%y"

# Easy pane splitting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quick session attach (for the auto-start)
bind a attach-session -t main

# Reload config easily
bind r source-file ~/.tmux.conf \; display "tmux reloaded!"
EOF
    echo "✓ Default .tmux.conf created (you can edit anytime)"
else
    echo "✓ .tmux.conf already exists (keeping your custom version)"
fi

# ==================== Auto-start tmux on SSH (add to .bashrc only once) ====================
BASHRC="${USER_HOME}/.bashrc"

if ! grep -q "tmux auto-start" "$BASHRC" 2>/dev/null; then
    cat >> "$BASHRC" << 'EOF'

# ================================================
# tmux auto-start on SSH (added by bootstrap stage 05)
# Only starts if you're logging in via SSH and not already in tmux
# ================================================
if [ -n "$SSH_CLIENT" ] && [ -z "$TMUX" ]; then
    # Attach to existing "main" session or create new one
    exec tmux new-session -A -s main
fi
EOF
    echo "✓ tmux auto-start added to .bashrc"
else
    echo "✓ tmux auto-start already configured in .bashrc"
fi

chown mark:mark "$TMUX_CONF" "$BASHRC"
chmod 644 "$TMUX_CONF" "$BASHRC"

echo "✓ Stage 05 complete!"
echo "   tmux will now auto-launch on every SSH login (session name: main)"
echo "   (Just SSH again to test - you'll land directly inside tmux)"
echo "   Pro tip: Inside tmux press Ctrl+b then ? to see all keybindings"
