#!/bin/bash
set -euo pipefail

echo ">>> Stage 06: Email setup (fetchmail + Alpine + msmtp) — FINAL FIXED VERSION"

# Target user home
USER_HOME="/home/mark"
if [ ! -d "$USER_HOME" ]; then
    echo "❌ User mark home directory not found - skipping"
    exit 1
fi

# Install required helpers (idempotent)
apt-get update -qq
apt-get install -y -qq procmail msmtp

# ==================== FORCE FIX: Remove old conflicting files ====================
rm -f "${USER_HOME}/.alpinerc"
echo "✓ Removed any old .alpinerc that was causing conflicts"

# ==================== Detect broken .pinerc and force reconfig (this fixes your current error) ====================
CONFIG_MARKER="${USER_HOME}/.email_configured"
PINERC="${USER_HOME}/.pinerc"

if [ -f "$PINERC" ] && ! grep -q "folder-collections" "$PINERC" 2>/dev/null; then
    echo "⚠️  Detected broken .pinerc (missing folder collections) — forcing full reconfig..."
    rm -f "$CONFIG_MARKER"
fi

# ==================== Ask for Gmail App Password ONLY IF NEEDED ====================
if [ ! -f "$CONFIG_MARKER" ]; then
    echo "=== Gmail Email Setup ==="
    echo "Gmail requires an App Password (not your regular password)."
    echo "1. Go to https://myaccount.google.com/apppasswords"
    echo "2. Select Mail → Generate → copy the 16-character password"
    echo ""
    read -s -p "Enter your Gmail App Password (16 chars): " EMAIL_PASS
    echo

    if [ "${#EMAIL_PASS}" -ne 16 ]; then
        echo "⚠️  Warning: App passwords are usually exactly 16 characters."
    fi

    echo "✓ Password received - configuring now..."
else
    echo "✓ Email already configured (skipping password prompt)"
fi

# ==================== Create Maildir (for Alpine) ====================
mkdir -p "${USER_HOME}/Maildir"/{cur,new,tmp}
chown -R mark:mark "${USER_HOME}/Maildir"
chmod -R 700 "${USER_HOME}/Maildir"

# ==================== .fetchmailrc (incoming IMAP from Gmail) ====================
FETCHMAILRC="${USER_HOME}/.fetchmailrc"

if [ ! -f "$FETCHMAILRC" ] || [ ! -f "$CONFIG_MARKER" ]; then
    cat > "$FETCHMAILRC" << EOF
# Mark's fetchmail config for Gmail IMAP
# Generated by bootstrap stage 06 - safe to rerun

set daemon 300

poll imap.gmail.com port 993
    proto imap
    user "markbbbnyc@gmail.com"
    pass "$EMAIL_PASS"
    ssl
    sslcertck
    keep
    fetchall
    mda "procmail -d %T"
EOF
    chmod 600 "$FETCHMAILRC"
    chown mark:mark "$FETCHMAILRC"
    echo "✓ .fetchmailrc created"
else
    echo "✓ .fetchmailrc already exists"
fi

# ==================== .procmailrc (deliver to Maildir) ====================
PROCMAILRC="${USER_HOME}/.procmailrc"

cat > "$PROCMAILRC" << 'EOF'
# Mark's procmail - delivers everything to Maildir for Alpine
MAILDIR=$HOME/Maildir
DEFAULT=$MAILDIR/

:0
*
$DEFAULT
EOF
chmod 644 "$PROCMAILRC"
chown mark:mark "$PROCMAILRC"
echo "✓ .procmailrc (re)created"

# ==================== .msmtprc (outgoing SMTP via Gmail) ====================
MSMTPRC="${USER_HOME}/.msmtprc"

if [ ! -f "$MSMTPRC" ] || [ ! -f "$CONFIG_MARKER" ]; then
    cat > "$MSMTPRC" << EOF
# Mark's msmtp config for Gmail SMTP
# Generated by bootstrap stage 06

account default
host smtp.gmail.com
port 587
auth on
user markbbbnyc@gmail.com
password $EMAIL_PASS
from markbbbnyc@gmail.com
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
EOF
    chmod 600 "$MSMTPRC"
    chown mark:mark "$MSMTPRC"
    echo "✓ .msmtprc created (sending enabled)"
else
    echo "✓ .msmtprc already exists"
fi

# ==================== .pinerc — ALWAYS overwritten with correct folder collections ====================
cat > "$PINERC" << 'EOF'
# Mark's Alpine config - FIXED for Maildir
# Generated by bootstrap stage 06

personal-name=Mark
user-domain=gmail.com

# Inbox = our local Maildir
inbox-path=~/Maildir

# Folder collections — THIS EXACT LINE fixes "No folder collections defined"
folder-collections="Maildir" {~/Maildir/}

# Sending via msmtp
sendmail-path=/usr/bin/ms
