#!/bin/bash
set -euo pipefail

echo ">>> Stage 06: Email setup (fetchmail + Alpine + msmtp for Gmail)"

# Target user home
USER_HOME="/home/mark"
if [ ! -d "$USER_HOME" ]; then
    echo "❌ User mark home directory not found - skipping"
    exit 1
fi

# Install required helpers (idempotent)
apt-get update -qq
apt-get install -y -qq procmail msmtp

# ==================== Ask for Gmail App Password ONLY ONCE ====================
CONFIG_MARKER="${USER_HOME}/.email_configured"

if [ ! -f "$CONFIG_MARKER" ]; then
    echo "=== Gmail Email Setup ==="
    echo "Gmail requires an App Password (not your regular password)."
    echo "1. Go to https://myaccount.google.com/apppasswords"
    echo "2. Select Mail → Generate → copy the 16-character password"
    echo ""
    read -s -p "Enter your Gmail App Password (16 chars): " EMAIL_PASS
    echo

    if [ "${#EMAIL_PASS}" -ne 16 ]; then
        echo "⚠️  Warning: App passwords are usually exactly 16 characters."
    fi

    echo "✓ Password received - configuring now..."
else
    echo "✓ Email already configured (skipping password prompt)"
fi

# ==================== Create Maildir (for Alpine) ====================
mkdir -p "${USER_HOME}/Maildir"/{cur,new,tmp}
chown -R mark:mark "${USER_HOME}/Maildir"
chmod -R 700 "${USER_HOME}/Maildir"

# ==================== .fetchmailrc (incoming IMAP from Gmail) ====================
FETCHMAILRC="${USER_HOME}/.fetchmailrc"

if [ ! -f "$FETCHMAILRC" ] || [ ! -f "$CONFIG_MARKER" ]; then
    cat > "$FETCHMAILRC" << EOF
# Mark's fetchmail config for Gmail IMAP
# Generated by bootstrap stage 06 - safe to rerun

set daemon 300

poll imap.gmail.com port 993
    proto imap
    user "markbbbnyc@gmail.com"
    pass "$EMAIL_PASS"
    ssl
    sslcertck
    keep
    fetchall
    mda "procmail -d %T"
EOF
    chmod 600 "$FETCHMAILRC"
    chown mark:mark "$FETCHMAILRC"
    echo "✓ .fetchmailrc created"
else
    echo "✓ .fetchmailrc already exists"
fi

# ==================== .procmailrc (deliver to Maildir) ====================
PROCMAILRC="${USER_HOME}/.procmailrc"

if [ ! -f "$PROCMAILRC" ]; then
    cat > "$PROCMAILRC" << 'EOF'
# Mark's procmail - delivers everything to Maildir for Alpine
MAILDIR=$HOME/Maildir
DEFAULT=$MAILDIR/

:0
*
$DEFAULT
EOF
    chmod 644 "$PROCMAILRC"
    chown mark:mark "$PROCMAILRC"
    echo "✓ .procmailrc created"
else
    echo "✓ .procmailrc already exists"
fi

# ==================== .msmtprc (outgoing SMTP via Gmail) ====================
MSMTPRC="${USER_HOME}/.msmtprc"

if [ ! -f "$MSMTPRC" ] || [ ! -f "$CONFIG_MARKER" ]; then
    cat > "$MSMTPRC" << EOF
# Mark's msmtp config for Gmail SMTP
# Generated by bootstrap stage 06

account default
host smtp.gmail.com
port 587
auth on
user markbbbnyc@gmail.com
password $EMAIL_PASS
from markbbbnyc@gmail.com
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
EOF
    chmod 600 "$MSMTPRC"
    chown mark:mark "$MSMTPRC"
    echo "✓ .msmtprc created (sending enabled)"
else
    echo "✓ .msmtprc already exists"
fi

# ==================== Alpine config (.pinerc) - only once ====================
PINERC="${USER_HOME}/.pinerc"

if [ ! -f "$PINERC" ]; then
    cat > "$PINERC" << 'EOF'
# Mark's Alpine config - minimal & ready for Gmail/Maildir
# Generated by bootstrap stage 06

personal-name=Mark
user-domain=gmail.com

# Inbox = our local Maildir
inbox-path=~/Maildir

# Folder collections
folder-collections=Maildir {~/Maildir}

# Sending via msmtp
sendmail-path=/usr/bin/msmtp -t

# Nice defaults
default-fcc=Sent
sent-mail=Sent
postponed-folder=Drafts
trash-folder=Trash

# Use vim/nvim as editor
editor=nvim

# Show full headers when needed
enable-full-header-cmd

# Disable annoying "new mail" beeps if you don't want them
enable-newmail-favicon
EOF
    chown mark:mark "$PINERC"
    chmod 644 "$PINERC"
    echo "✓ .pinerc created (Alpine ready)"
else
    echo "✓ .pinerc already exists (keeping your version)"
fi

# ==================== Auto-start fetchmail on reboot (idempotent) ====================
if ! crontab -u mark -l 2>/dev/null | grep -q "fetchmail"; then
    (crontab -u mark -l 2>/dev/null; echo "@reboot /usr/bin/fetchmail") | crontab -u mark -
    echo "✓ Added @reboot cron to start fetchmail daemon"
else
    echo "✓ fetchmail cron already set"
fi

# ==================== Final marker so we never ask for password again ====================
if [ ! -f "$CONFIG_MARKER" ]; then
    touch "$CONFIG_MARKER"
    chown mark:mark "$CONFIG_MARKER"
    echo "✓ Email configuration complete (password saved securely)"
fi

# Start fetchmail now if it's not running
if ! pgrep -u mark fetchmail >/dev/null; then
    su - mark -c "fetchmail" || true
    echo "✓ fetchmail daemon started"
else
    echo "✓ fetchmail already running"
fi

echo "✓ Stage 06 complete!"
echo ""
echo "=== How to use your email ==="
echo "• Run 'alpine' → you are now in your full email client"
echo "• First fetch: just wait 30 seconds or run 'fetchmail' manually"
echo "• Sending email works directly from Alpine (uses your Gmail account)"
echo "• All mail is stored locally in ~/Maildir"
echo "• You can rerun the bootstrap anytime - nothing will be overwritten"
echo ""
echo "Pro tip: Inside Alpine press '?' for help or 'C' to compose."
